# Generated by Django 4.2.5 on 2023-09-14 18:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueagency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.UploadToPathAndRename('agency_logos/')),
        ),
    ]
